import type {
    Display,
    FlexDirection,
    AlignItems,
    JustifyContent,
    GapToken,
    PaddingToken,
    PaddingXToken,
    PaddingYToken,
    MarginTopToken,
    MarginBottomToken,
    MarginXToken,
    BackgroundToken,
    RadiusToken,
    BorderToken,
    PositionToken,
    OverflowToken,
    WidthToken,
    HeightToken,
    MaxWidthToken,
    MaxHeightToken,
    FlexToken,
    TransitionToken,
    TextAlign
} from './types';

/**
 * Style-related props shared by all box-like primitives: `Box`, `Row`, `Stack`,
 * `Surface`, `Card`, `Alert`, etc.
 *
 * Every token resolves through an explicit lookup table below, and that is a hard
 * requirement rather than a style preference: these classes are generated by
 * Tailwind, whose scanner only recognises a class name it can see as a complete
 * literal in a source file. The previous implementation built them by
 * concatenation (`\`gap-${props.gap}\``), which a scanner cannot follow — every
 * such utility would silently fail to be generated. Adding a token means adding
 * a row to a table here, never interpolating one.
 */
export interface BoxStyleProps {
    display?: Display;
    direction?: FlexDirection;
    align?: AlignItems;
    justify?: JustifyContent;
    wrap?: boolean;
    gap?: GapToken;

    p?: PaddingToken;
    px?: PaddingXToken;
    py?: PaddingYToken;

    m?: '0';
    mt?: MarginTopToken;
    mb?: MarginBottomToken;
    mx?: MarginXToken;

    bg?: BackgroundToken;
    radius?: RadiusToken;
    border?: BorderToken;
    position?: PositionToken;
    overflow?: OverflowToken;

    width?: WidthToken;
    height?: HeightToken;
    maxW?: MaxWidthToken;
    maxH?: MaxHeightToken;
    flex?: FlexToken;

    textAlign?: TextAlign;

    /**
     * The nowrap + ellipsis + overflow-hidden triad. `Text` has always had this;
     * box-like primitives did not, which is why apps kept writing it by hand on
     * the wrapper that actually owns the width constraint.
     */
    truncate?: boolean;

    shrink?: '0';
    minH?: '0';
    minW?: '0';

    inset?: '0';
    top?: '0' | '1';
    left?: '0' | '1';
    bottom?: '0' | '1';
    right?: '0' | '1';

    zIndex?: '5' | '10' | '20';

    transition?: TransitionToken;
    cursor?: 'pointer';
    selectNone?: boolean;
}

const displayMap: Record<Display, string> = {
    'flex': 'flex',
    'inline-flex': 'inline-flex',
    'grid': 'grid',
    'block': 'block',
    'none': 'hidden'
};

const directionMap: Record<FlexDirection, string> = {
    'row': 'flex-row',
    'column': 'flex-col',
    'row-reverse': 'flex-row-reverse'
};

const alignMap: Record<AlignItems, string> = {
    start: 'items-start',
    center: 'items-center',
    end: 'items-end'
};

const justifyMap: Record<JustifyContent, string> = {
    start: 'justify-start',
    center: 'justify-center',
    end: 'justify-end',
    between: 'justify-between',
    around: 'justify-around'
};

/*
 * Spacing. bravais's token names are rem-derived (`05` = 0.5rem) while Tailwind's
 * are multiples of its 0.25rem base, so the two scales are related but not
 * interchangeable — `p-1` means 1rem here and 0.25rem there. The tables are the
 * only place that translation exists.
 *
 * Three steps fall off Tailwind's grid entirely (0.1rem, 0.2rem, 0.35rem) and use
 * its arbitrary-value syntax, which is the whole reason for adopting it: a closed
 * enum had nowhere to put a value the scale did not anticipate.
 */
const gapMap: Record<GapToken, string> = {
    '0': 'gap-0',
    '01': 'gap-[0.1rem]',
    '0125': 'gap-0.5',
    '02': 'gap-[0.2rem]',
    '025': 'gap-1',
    '035': 'gap-[0.35rem]',
    '0375': 'gap-1.5',
    '05': 'gap-2',
    '0625': 'gap-2.5',
    '075': 'gap-3',
    '1': 'gap-4',
    '1-5': 'gap-6',
    '2': 'gap-8',
    '3': 'gap-12'
};

const paddingMap: Record<PaddingToken, string> = {
    '0': 'p-0',
    '025': 'p-1',
    '05': 'p-2',
    '075': 'p-3',
    '1': 'p-4',
    '1-5': 'p-6',
    '2': 'p-8',
    '3': 'p-12'
};

const paddingXMap: Record<PaddingXToken, string> = {
    '0': 'px-0',
    '025': 'px-1',
    '05': 'px-2',
    '075': 'px-3',
    '1': 'px-4',
    '1-5': 'px-6',
    '2': 'px-8',
    '3': 'px-12'
};

const paddingYMap: Record<PaddingYToken, string> = {
    '0': 'py-0',
    '025': 'py-1',
    '05': 'py-2',
    '075': 'py-3',
    '1': 'py-4',
    '1-5': 'py-6',
    '2': 'py-8',
    '3': 'py-12'
};

const marginTopMap: Record<MarginTopToken, string> = {
    '0': 'mt-0',
    '025': 'mt-1',
    '05': 'mt-2',
    '075': 'mt-3',
    '1': 'mt-4',
    '1-5': 'mt-6',
    '2': 'mt-8',
    '3': 'mt-12'
};

const marginBottomMap: Record<MarginBottomToken, string> = {
    '0': 'mb-0',
    '025': 'mb-1',
    '05': 'mb-2',
    '075': 'mb-3',
    '1': 'mb-4',
    '1-5': 'mb-6',
    '2': 'mb-8',
    '3': 'mb-12'
};

/* Radii and colours resolve through `tailwind.css`, which maps bravais's tokens
   into Tailwind's `--radius-*` and `--color-*` namespaces. */
const radiusMap: Record<RadiusToken, string> = {
    'xs': 'rounded-xs',
    'sm': 'rounded-sm',
    'md': 'rounded-md',
    'lg': 'rounded-lg',
    'xl': 'rounded-xl',
    '2xl': 'rounded-2xl',
    'full': 'rounded-full'
};

const backgroundMap: Record<BackgroundToken, string> = {
    'transparent': 'bg-transparent',
    'hover': 'bg-hover',
    'bg': 'bg-page',
    'content': 'bg-content',
    'surface-1': 'bg-surface-1',
    'surface-2': 'bg-surface-2',
    'surface-3': 'bg-surface-3',
    'glass': 'bg-glass',
    'glass-secondary': 'bg-glass-secondary',
    'overlay': 'bg-overlay'
};

/* In Tailwind's model a border is a width plus a colour, so each token emits both. */
const borderMap: Record<BorderToken, string> = {
    'soft': 'border border-soft',
    'strong': 'border border-edge-strong',
    'glass': 'border border-edge-glass',
    'transparent': 'border border-transparent',
    'none': 'border-0',
    'top-soft': 'border-t border-soft',
    'bottom-soft': 'border-b border-soft',
    'left-soft': 'border-l border-soft',
    'right-soft': 'border-r border-soft',
    'bottom-glass': 'border-b border-edge-glass',
    'bottom-none': 'border-b-0'
};

const positionMap: Record<PositionToken, string> = {
    relative: 'relative',
    sticky: 'sticky',
    absolute: 'absolute',
    fixed: 'fixed'
};

const overflowMap: Record<OverflowToken, string> = {
    'auto': 'overflow-auto',
    'hidden': 'overflow-hidden',
    'x-auto': 'overflow-x-auto',
    'x-scroll': 'overflow-x-scroll',
    'y-auto': 'overflow-y-auto',
    'y-scroll': 'overflow-y-scroll'
};

const widthMap: Record<WidthToken, string> = {
    'max': 'w-full',
    '50': 'w-1/2',
    'vw-max': 'w-screen'
};

const heightMap: Record<HeightToken, string> = {
    'max': 'h-full',
    'vh-max': 'h-dvh'
};

const maxWidthMap: Record<MaxWidthToken, string> = { max: 'max-w-full' };

const maxHeightMap: Record<MaxHeightToken, string> = { max: 'max-h-full' };

const flexMap: Record<FlexToken, string> = { '1': 'flex-1' };

const marginXMap: Record<MarginXToken, string> = { auto: 'mx-auto' };

const textAlignMap: Record<TextAlign, string> = {
    left: 'text-left',
    center: 'text-center',
    right: 'text-right'
};

const insetMap = {
    top: {
        '0': 'top-0',
        '1': 'top-4'
    },
    left: {
        '0': 'left-0',
        '1': 'left-4'
    },
    bottom: {
        '0': 'bottom-0',
        '1': 'bottom-4'
    },
    right: {
        '0': 'right-0',
        '1': 'right-4'
    }
} as const;

const zIndexMap = {
    '5': 'z-[5]',
    '10': 'z-10',
    '20': 'z-20'
} as const;

export const buildBoxClasses = (props: BoxStyleProps): string[] => {
    const classes: string[] = [];

    if (props.display) classes.push(displayMap[props.display]);
    if (props.direction) classes.push(directionMap[props.direction]);
    if (props.align) classes.push(alignMap[props.align]);
    if (props.justify) classes.push(justifyMap[props.justify]);
    if (props.wrap) classes.push('flex-wrap');
    if (props.gap) classes.push(gapMap[props.gap]);

    if (props.p !== undefined) classes.push(paddingMap[props.p]);
    if (props.px !== undefined) classes.push(paddingXMap[props.px]);
    if (props.py !== undefined) classes.push(paddingYMap[props.py]);

    if (props.m !== undefined) classes.push('m-0');
    if (props.mt) classes.push(marginTopMap[props.mt]);
    if (props.mb) classes.push(marginBottomMap[props.mb]);
    if (props.mx) classes.push(marginXMap[props.mx]);

    if (props.bg) classes.push(backgroundMap[props.bg]);
    if (props.radius) classes.push(radiusMap[props.radius]);
    if (props.border) classes.push(borderMap[props.border]);
    if (props.position) classes.push(positionMap[props.position]);
    if (props.overflow) classes.push(overflowMap[props.overflow]);

    if (props.width) classes.push(widthMap[props.width]);
    if (props.height) classes.push(heightMap[props.height]);
    if (props.maxW) classes.push(maxWidthMap[props.maxW]);
    if (props.maxH) classes.push(maxHeightMap[props.maxH]);
    if (props.flex) classes.push(flexMap[props.flex]);

    if (props.textAlign) classes.push(textAlignMap[props.textAlign]);
    if (props.truncate) classes.push('truncate');

    if (props.shrink === '0') classes.push('shrink-0');
    if (props.minH === '0') classes.push('min-h-0');
    if (props.minW === '0') classes.push('min-w-0');

    if (props.inset === '0') classes.push('inset-0');
    if (props.top !== undefined) classes.push(insetMap.top[props.top]);
    if (props.left !== undefined) classes.push(insetMap.left[props.left]);
    if (props.bottom !== undefined) classes.push(insetMap.bottom[props.bottom]);
    if (props.right !== undefined) classes.push(insetMap.right[props.right]);

    if (props.zIndex) classes.push(zIndexMap[props.zIndex]);

    /* `transition-fast` / `transition-normal` are composites, not utilities: they
       name a property list and a duration together. They stay in composites.css. */
    if (props.transition === 'fast') classes.push('transition-fast');
    if (props.transition === 'normal') classes.push('transition-normal');
    if (props.cursor === 'pointer') classes.push('cursor-pointer');
    if (props.selectNone) classes.push('select-none');

    return classes;
};

/**
 * Keys of `BoxStyleProps`. Used by primitives to strip style-only props
 * from the rest passed through to the DOM element.
 */
export const BOX_STYLE_KEYS = [
    'display', 'direction', 'align', 'justify', 'wrap', 'gap',
    'p', 'px', 'py', 'm', 'mt', 'mb', 'mx',
    'bg', 'radius', 'border', 'position', 'overflow',
    'width', 'height', 'maxW', 'maxH', 'flex',
    'textAlign', 'truncate',
    'shrink', 'minH', 'minW',
    'inset', 'top', 'left', 'bottom', 'right',
    'zIndex',
    'transition', 'cursor', 'selectNone'
] as const;

export const splitBoxProps = <T extends BoxStyleProps>(props: T): {
    styleProps: BoxStyleProps;
    rest: Omit<T, keyof BoxStyleProps>;
} => {
    const styleProps: Record<string, unknown> = {};
    const rest: Record<string, unknown> = {};

    for (const key of Object.keys(props)) {
        if ((BOX_STYLE_KEYS as readonly string[]).includes(key)) {
            styleProps[key] = (props as Record<string, unknown>)[key];
        } else {
            rest[key] = (props as Record<string, unknown>)[key];
        }
    }

    return {
        styleProps: styleProps as BoxStyleProps,
        rest: rest as Omit<T, keyof BoxStyleProps>
    };
};
